#!/bin/bash

echo "====================================="
echo "GitHub 仓库推送助手"
echo "====================================="
echo ""
echo "请确认以下事项："
echo ""
echo "1. 仓库是否已创建？"
echo "   - 如果没有，请访问: https://github.com/new"
echo "   - 仓库名称: NIHONGmodel"
echo "   - 不要初始化 README"
echo ""
echo "2. 如果仓库已存在但是私有的："
echo "   - 访问: https://github.com/owanzz/NIHONGmodel/settings"
echo "   - 在 Danger Zone 中改为 Public"
echo ""
echo "3. 创建 Personal Access Token："
echo "   - 访问: https://github.com/settings/tokens"
echo "   - 点击 'Generate new token (classic)'"
echo "   - 勾选 'repo' 权限"
echo "   - 复制生成的 token"
echo ""
echo "4. 推送代码："
echo "   git push -u origin main"
echo "   用户名: owanzz"
echo "   密码: [粘贴您的 Personal Access Token]"
echo ""
echo "====================================="
echo "或者使用 GitHub CLI (如果已安装):"
echo "   gh auth login"
echo "   git push -u origin main"
echo "====================================="