#!/bin/bash

echo "==================================="
echo "Nihong iOS Home Screen"
echo "==================================="
echo ""
echo "服务器已在端口 3333 启动！"
echo ""
echo "请在浏览器中打开以下任一地址："
echo ""
echo "1. http://localhost:3333"
echo "2. http://127.0.0.1:3333"
echo ""
echo "或者直接打开文件："
echo "file:///workspaces/VSCodeTemplateOwanTest/nihong/index.html"
echo ""
echo "==================================="
echo "项目特性："
echo "- iOS 风格主屏幕"
echo "- 渐变背景"
echo "- 应用图标网格"
echo "- 底部 Dock 栏"
echo "- 响应式设计"
echo "==================================="